/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.portales.domingo.progra2.grupo12.farmaciajutiapa.vista;

import com.portales.domingo.progra2.grupo12.farmaciajutiapa.controlador.ConectaBD;
import com.portales.domingo.progra2.grupo12.farmaciajutiapa.controlador.Util;
import com.portales.domingo.progra2.grupo12.farmaciajutiapa.dao.accesoDAO;
import com.portales.domingo.progra2.grupo12.farmaciajutiapa.modelo.acceso;
import com.portales.domingo.progra2.grupo12.farmaciajutiapa.modelo.estado_civil;
import com.portales.domingo.progra2.grupo12.farmaciajutiapa.modelo.estadoCivilItem;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Edinson Ruano
 */
public class facceso extends javax.swing.JFrame {
    
    private accesoDAO aDAO = null;
    private acceso miAcceso=null;
    private DefaultTableModel modelo=null;
    private int fila = 0;

    /**
     * Creates new form facceso
     */
    public facceso() {
        initComponents();
        llenaListado();
        limpiaCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblId_acceso = new javax.swing.JLabel();
        txtid_acceso = new javax.swing.JTextField();
        lblnombre_acceso = new javax.swing.JLabel();
        txtnombre_acceso = new javax.swing.JTextField();
        lblpagina_acceso = new javax.swing.JLabel();
        txtpagina_acceso = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDatosAcceso = new javax.swing.JTable();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblId_acceso.setText("Id Acceso");

        lblnombre_acceso.setText("Nombre Acceso");

        lblpagina_acceso.setText("Pagina Acceso");

        btnAgregar.setText("Agregar");

        btnModificar.setText("Modificar");

        btnEliminar.setText("Eliminar");

        btnNuevo.setText("Nuevo");

        TablaDatosAcceso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Acceso", "Nombre Acceso", "Pagina Acceso"
            }
        ));
        TablaDatosAcceso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDatosAccesoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaDatosAcceso);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar)
                        .addGap(54, 54, 54)
                        .addComponent(btnNuevo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblnombre_acceso)
                                    .addComponent(lblId_acceso))
                                .addGap(85, 85, 85))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblpagina_acceso)
                                .addGap(90, 90, 90)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtnombre_acceso, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(txtid_acceso)
                            .addComponent(txtpagina_acceso))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId_acceso)
                    .addComponent(txtid_acceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnombre_acceso)
                    .addComponent(txtnombre_acceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpagina_acceso)
                    .addComponent(txtpagina_acceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(btnNuevo))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        agregar();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void TablaDatosPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDatosPersonaMouseClicked
        
    }//GEN-LAST:event_TablaDatosPersonaMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        modificar();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiaCampos();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void TablaDatosAccesoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDatosAccesoMouseClicked
        fila = TablaDatosAcceso.getSelectedRow();
        if(fila == -1){
            JOptionPane.showMessageDialog(null, "Acceso no seleccionado");
        }else{
            this.txtid_acceso.setText((String)TablaDatosAcceso.getValueAt(fila,0));
            this.txtnombre_acceso.setText((String)TablaDatosAcceso.getValueAt(fila,1));
            this.txtpagina_acceso.setText((String)TablaDatosAcceso.getValueAt(fila,2));
        }
    }//GEN-LAST:event_TablaDatosAccesoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(facceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(facceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(facceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(facceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new facceso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaDatosAcceso;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblId_acceso;
    private javax.swing.JLabel lblnombre_acceso;
    private javax.swing.JLabel lblpagina_acceso;
    private javax.swing.JTextField txtid_acceso;
    private javax.swing.JTextField txtnombre_acceso;
    private javax.swing.JTextField txtpagina_acceso;
    // End of variables declaration//GEN-END:variables


    private void limpiaCampos() {
        try{
            this.txtid_acceso.setText("");
            this.txtnombre_acceso.setText("");
            this.txtpagina_acceso.setText("");

        }catch(Exception e){
            Util.printException("facceso.limpiaCampos", e);
        }                
    }
    
    
    public void limpiaTabla(){
        try{        
            for(int i=0;i<=TablaDatosAcceso.getRowCount();i++){
                modelo.removeRow(i);
                i = i - 1;
            }
        }catch(Exception e){
            Util.printException("facceso.limpiaTabla", e);
        }        
    }

    private void llenaListado() {
        List<acceso> listaAccesos = null;
        
        try{
            aDAO = new accesoDAO();
            listaAccesos = new ArrayList<>();
            listaAccesos = aDAO.seleccionaTodo();

            Object[]pObj=new Object[8];

            modelo = (DefaultTableModel)TablaDatosAcceso.getModel();

            for(acceso p:listaAccesos){
                pObj[0] = p.getId_persona();
                pObj[1] = p.getPrimer_nombre();
                pObj[2] = p.getSegundo_nombre();
                pObj[3] = p.getPrimer_apellido();
                pObj[4] = p.getSegundo_apellido();
                pObj[5] = p.getId_genero();
                pObj[6] = p.getFecha_de_nacimiento();
                pObj[7] = p.getId_estado_civil();
                modelo.addRow(pObj);

            }
            TablaDatosAcceso.setModel(modelo);
        }catch(Exception e){
            Util.printException("facceso.llenaListado", e);
        }
    }

    
    
    private void agregar(){
        
        try{
            miAcceso = new acceso(Util.str2int(this.txtid_persona.getText()),
                                    this.txtprimer_nombre.getText(),
                                    this.txtsegundo_nombre.getText(),
                                    this.txtprimer_apellido.getText(),
                                    this.txtsegundo_apellido.getText(),
                                    Util.int2cbx( this.cbxid_genero.getSelectedIndex() ),
                                    Util.str2date(this.txtfecha_de_nacimiento.getText()),
                                    Util.int2cbx( this.cbxid_estado_civil.getSelectedIndex() ));
            
            if ( aDAO.inserta(miAcceso) ){
                JOptionPane.showMessageDialog(null, "Usuario ingresado");
                limpiaTabla();
                limpiaCampos();
                llenaListado();
            }
                    
            
        }catch(Exception e){
            Util.printException("facceso.agregar", e);
        }
    }
    
    private void modificar(){
        try{
            miAcceso = new acceso(Util.str2int(this.txtid_persona.getText()),
                                    this.txtprimer_nombre.getText(),
                                    this.txtsegundo_nombre.getText(),
                                    this.txtprimer_apellido.getText(),
                                    this.txtsegundo_apellido.getText(),
                                    this.cbxid_genero.getSelectedIndex(),
                                    Util.str2date(this.txtfecha_de_nacimiento.getText()),
                                    this.cbxid_estado_civil.getSelectedIndex());
            
            if ( aDAO.actualiza(miAcceso) ){
                JOptionPane.showMessageDialog(null, "Acceso actualizada");
                limpiaTabla();
                limpiaCampos();
                llenaListado();
            }

        }catch(Exception e){
            Util.printException("facceso.modificar", e);
        }
    }
    
    

    private void eliminar(){
        try{        
            fila = TablaDatosAcceso.getSelectedRow();
            if(fila == -1){
                JOptionPane.showMessageDialog(null, "Debe seleccionar fila");
            }else{
                if ( aDAO.elimina( Util.str2int((String)TablaDatosAcceso.getValueAt(fila,0)) ) ){
                    JOptionPane.showMessageDialog(null, "Acceso eliminada");
                    limpiaTabla();
                    limpiaCampos();
                    llenaListado();
                }
            }
        }catch(Exception e){
            Util.printException("facceso.eliminar", e);
        }        
    }    
    
}
