/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.portales.domingo.progra2.grupo12.farmaciajutiapa.vista;

import com.portales.domingo.progra2.grupo12.farmaciajutiapa.controlador.Util;
import com.portales.domingo.progra2.grupo12.farmaciajutiapa.dao.compra_detalleDAO;
import com.portales.domingo.progra2.grupo12.farmaciajutiapa.modelo.compra_detalle;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Edinson Ruano
 */
public class fcompra_detalle extends javax.swing.JFrame {
    
    private compra_detalleDAO cdDAO = null;
    private compra_detalle miCompraDetalle=null;
    private DefaultTableModel modelo=null;
    private int fila = 0;

    /**
     * Creates new form fcompra_detalle
     */
    public fcompra_detalle() {
        initComponents();
        
        //Permite cerrar la BD cuando se cierra la ventana
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent event) {
                if(cdDAO!=null)
                    cdDAO.cierra();
                    dispose();
                    System.exit(0);
            }
        });

        llenaListado();
        limpiaCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblide_compra_detalle = new javax.swing.JLabel();
        txtide_compra_detalle = new javax.swing.JTextField();
        lblid_compra = new javax.swing.JLabel();
        txtid_compra = new javax.swing.JTextField();
        lblid_marca_producto = new javax.swing.JLabel();
        txtid_marca_producto = new javax.swing.JTextField();
        lblid_tipo_producto = new javax.swing.JLabel();
        txtid_tipo_producto = new javax.swing.JTextField();
        lblid_producto = new javax.swing.JLabel();
        txtid_producto = new javax.swing.JTextField();
        lblprecio_unitario_compra = new javax.swing.JLabel();
        txtprecio_unitario_compra = new javax.swing.JTextField();
        lblcantidad = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        brnEliminar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDatosCompraDetalle = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblide_compra_detalle.setText("Id compra detalle");

        lblid_compra.setText("Id compra");

        lblid_marca_producto.setText("Id marca producto");

        lblid_tipo_producto.setText("Id tipo producto");

        lblid_producto.setText("Id producto");

        lblprecio_unitario_compra.setText("Precio unitario compra");

        lblcantidad.setText("Cantidad");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        brnEliminar.setText("Eliminar");
        brnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnEliminarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        TablaDatosCompraDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Compra Detalle", "Id Compra", "Id Marca Producto", "Id Tipo Producto", "Id Producto", "Precio Unitario Compra", "Cantidad"
            }
        ));
        TablaDatosCompraDetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDatosCompraDetalleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaDatosCompraDetalle);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblide_compra_detalle)
                                    .addComponent(lblid_compra)
                                    .addComponent(lblid_marca_producto)
                                    .addComponent(lblid_tipo_producto)
                                    .addComponent(lblid_producto))
                                .addGap(72, 72, 72)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtide_compra_detalle, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                    .addComponent(txtid_compra)
                                    .addComponent(txtid_marca_producto)
                                    .addComponent(txtid_tipo_producto)
                                    .addComponent(txtid_producto)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblprecio_unitario_compra)
                                    .addComponent(lblcantidad))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtprecio_unitario_compra)
                                    .addComponent(txtcantidad))))
                        .addGap(29, 29, 29)
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificar)
                        .addGap(18, 18, 18)
                        .addComponent(brnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNuevo)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblide_compra_detalle)
                    .addComponent(txtide_compra_detalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblid_compra)
                    .addComponent(txtid_compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtid_marca_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblid_marca_producto))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblid_tipo_producto)
                    .addComponent(txtid_tipo_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblid_producto)
                    .addComponent(txtid_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblprecio_unitario_compra)
                    .addComponent(txtprecio_unitario_compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblcantidad)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAgregar)
                        .addComponent(btnModificar)
                        .addComponent(brnEliminar)
                        .addComponent(btnNuevo)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaDatosCompraDetalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDatosCompraDetalleMouseClicked
        try{
            fila = TablaDatosCompraDetalle.getSelectedRow();
            if(fila == -1){
                JOptionPane.showMessageDialog(null, "Compra detalle no seleccionado");
            }else{
                String idCompraDetalle=(String)TablaDatosCompraDetalle.getValueAt(fila,0).toString();
                String idCompra=(String)TablaDatosCompraDetalle.getValueAt(fila,1).toString();
                String idMarcaProducto=(String)TablaDatosCompraDetalle.getValueAt(fila,2).toString();
                String idTipoProducto=(String)TablaDatosCompraDetalle.getValueAt(fila,3).toString();
                String idProducto=(String)TablaDatosCompraDetalle.getValueAt(fila,4).toString();
                String PrecioUnitarioCompra=(String)TablaDatosCompraDetalle.getValueAt(fila,5);
                String cantidad=(String)TablaDatosCompraDetalle.getValueAt(fila,6);
                this.txtide_compra_detalle.setText(idCompraDetalle);
                this.txtid_compra.setText(idCompra);
                this.txtid_marca_producto.setText(idMarcaProducto);
                this.txtid_tipo_producto.setText(idTipoProducto);
                this.txtid_producto.setText(idProducto);
                this.txtprecio_unitario_compra.setText(PrecioUnitarioCompra);                
                this.txtcantidad.setText(cantidad);                                
            }
        }catch(Exception e){
            Util.printException("fcompra_detalle.TablaDatosCompraDetalleMouseClicked", e);
        }          
    }//GEN-LAST:event_TablaDatosCompraDetalleMouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        agregar();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        modificar();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void brnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnEliminarActionPerformed
        eliminar();
    }//GEN-LAST:event_brnEliminarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiaCampos();
    }//GEN-LAST:event_btnNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fcompra_detalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fcompra_detalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fcompra_detalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fcompra_detalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fcompra_detalle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaDatosCompraDetalle;
    private javax.swing.JButton brnEliminar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcantidad;
    private javax.swing.JLabel lblid_compra;
    private javax.swing.JLabel lblid_marca_producto;
    private javax.swing.JLabel lblid_producto;
    private javax.swing.JLabel lblid_tipo_producto;
    private javax.swing.JLabel lblide_compra_detalle;
    private javax.swing.JLabel lblprecio_unitario_compra;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtid_compra;
    private javax.swing.JTextField txtid_marca_producto;
    private javax.swing.JTextField txtid_producto;
    private javax.swing.JTextField txtid_tipo_producto;
    private javax.swing.JTextField txtide_compra_detalle;
    private javax.swing.JTextField txtprecio_unitario_compra;
    // End of variables declaration//GEN-END:variables


    private void limpiaCampos() {
        try{
            this.txtide_compra_detalle.setText("");
            this.txtid_compra.setText("");
            this.txtid_marca_producto.setText("");
            this.txtid_tipo_producto.setText("");
            this.txtid_producto.setText("");
            this.txtprecio_unitario_compra.setText("");
            this.txtcantidad.setText("");
        }catch(Exception e){
            Util.printException("fcompra_detalle.limpiaCampos", e);
        }                
    }
    
    
    public void limpiaTabla(){
        int filaRestante=0;
        try{        
            for(int i=0;i<=TablaDatosCompraDetalle.getRowCount();i++){
                modelo.removeRow(i);
                i = i - 1;
                filaRestante=modelo.getRowCount();
                if(filaRestante==0){
                    break;
                }
            }
        }catch(Exception e){
            Util.printException("fcompra_detalle.limpiaTabla", e);
        }        
    }

    private void llenaListado() {
        List<compra_detalle> listaCompraDetalle = null;
        
        try{
            cdDAO = new compra_detalleDAO();
            listaCompraDetalle = new ArrayList<>();
            listaCompraDetalle = cdDAO.seleccionaTodo();

            Object[]pObj=new Object[7];

            modelo = (DefaultTableModel)TablaDatosCompraDetalle.getModel();

            for(compra_detalle p:listaCompraDetalle){
                pObj[0] = p.getId_compra_detalle();
                pObj[1] = p.getId_compra();
                pObj[2] = p.getId_marca_producto();
                pObj[3] = p.getId_tipo_producto();
                pObj[4] = p.getId_producto();
                pObj[5] = p.getPrecio_unitario_compra();
                pObj[6] = p.getCantidad();
                modelo.addRow(pObj);
            }
            TablaDatosCompraDetalle.setModel(modelo);
        }catch(Exception e){
            Util.printException("fcompra_detalle.llenaListado", e);
        }
    }

    
    
    private void agregar(){
        
        try{
            miCompraDetalle = new compra_detalle(   Util.str2int( this.txtide_compra_detalle.getText() ),
                                                    Util.str2int( this.txtid_compra.getText() ),
                                                    Util.str2int( this.txtid_marca_producto.getText() ),
                                                    Util.str2int( this.txtid_tipo_producto.getText() ),
                                                    Util.str2int( this.txtid_producto.getText() ),
                                                    Util.str2double( this.txtprecio_unitario_compra.getText() ),
                                                    Util.str2int( this.txtcantidad.getText() ) );
            
            
            if ( cdDAO.inserta( miCompraDetalle ) ){
                JOptionPane.showMessageDialog(null, "Compra detalle ingresada");
                limpiaTabla();
                limpiaCampos();
                llenaListado();
            }
                    
            
        }catch(Exception e){
            Util.printException("fcompra_detalle.agregar", e);
        }
    }
    
    private void modificar(){
        try{
            miCompraDetalle = new compra_detalle(   Util.str2int( this.txtide_compra_detalle.getText() ),
                                                    Util.str2int( this.txtid_compra.getText() ),
                                                    Util.str2int( this.txtid_marca_producto.getText() ),
                                                    Util.str2int( this.txtid_tipo_producto.getText() ),
                                                    Util.str2int( this.txtid_producto.getText() ),
                                                    Util.str2double( this.txtprecio_unitario_compra.getText() ),
                                                    Util.str2int( this.txtcantidad.getText() ) );
            
            if ( cdDAO.actualiza( miCompraDetalle ) ){
                JOptionPane.showMessageDialog(null, "Compra detalle actualizada");
                limpiaTabla();
                limpiaCampos();
                llenaListado();
            }

        }catch(Exception e){
            Util.printException("fcompra_detalle.modificar", e);
        }
    }
    
    

    private void eliminar(){
        try{        
            fila = TablaDatosCompraDetalle.getSelectedRow();
            if(fila == -1){
                JOptionPane.showMessageDialog(null, "Debe seleccionar fila");
            }else{
                if ( cdDAO.elimina( Util.str2int((String)TablaDatosCompraDetalle.getValueAt(fila,0).toString()) ) ){
                    JOptionPane.showMessageDialog(null, "Compra detalle eliminada");
                    limpiaTabla();
                    limpiaCampos();
                    llenaListado();
                }
            }
        }catch(Exception e){
            Util.printException("fcompra_detalle.eliminar", e);
        }        
    }    
 
}
