/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.portales.domingo.progra2.grupo12.farmaciajutiapa.vista;


import com.portales.domingo.progra2.grupo12.farmaciajutiapa.controlador.Util;
import com.portales.domingo.progra2.grupo12.farmaciajutiapa.dao.compraDAO;
import com.portales.domingo.progra2.grupo12.farmaciajutiapa.modelo.compra;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Edinson Ruano
 */
public class fcompra extends javax.swing.JFrame {
    
    private compraDAO cDAO = null;
    private compra miCompra=null;
    private DefaultTableModel modelo=null;
    private int fila = 0;

    /**
     * Creates new form fcompra
     */
    public fcompra() {
        initComponents();
        
        //Permite cerrar la BD cuando se cierra la ventana
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent event) {
                if(cDAO!=null)
                    cDAO.cierra();
                    dispose();
                    System.exit(0);
            }
        });

        llenaListado();
        limpiaCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblid_compra = new javax.swing.JLabel();
        txtid_compra = new javax.swing.JTextField();
        lblid_proveedor = new javax.swing.JLabel();
        txtid_proveedor = new javax.swing.JTextField();
        lblfecha_compra = new javax.swing.JLabel();
        txtfecha_compra = new javax.swing.JTextField();
        lblnumero_facctura = new javax.swing.JLabel();
        txtnumero_factura = new javax.swing.JTextField();
        lblmonto_total = new javax.swing.JLabel();
        txtmonto_total = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDatosCompra = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Mantenimiento de compra");

        lblid_compra.setText("Id compra");

        txtid_compra.setEditable(false);

        lblid_proveedor.setText("Id proveedor");

        lblfecha_compra.setText("Fecha compra");

        lblnumero_facctura.setText("Numero factura");

        lblmonto_total.setText("Monto total");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        TablaDatosCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Compra", "Id Proveedor", "Fecha Compra", "Numero Factura", "Monto Total"
            }
        ));
        TablaDatosCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDatosCompraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TablaDatosCompraMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(TablaDatosCompra);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblid_compra)
                            .addComponent(lblid_proveedor)
                            .addComponent(lblfecha_compra)
                            .addComponent(lblnumero_facctura)
                            .addComponent(lblmonto_total))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtid_compra, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(txtid_proveedor)
                            .addComponent(txtfecha_compra)
                            .addComponent(txtnumero_factura)
                            .addComponent(txtmonto_total)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNuevo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblid_compra)
                    .addComponent(txtid_compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblid_proveedor)
                    .addComponent(txtid_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfecha_compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblfecha_compra))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblnumero_facctura)
                    .addComponent(txtnumero_factura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblmonto_total)
                    .addComponent(txtmonto_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(btnNuevo))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaDatosCompraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDatosCompraMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaDatosCompraMouseEntered

    private void TablaDatosCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDatosCompraMouseClicked
        try{
            fila = TablaDatosCompra.getSelectedRow();
            if(fila == -1){
                JOptionPane.showMessageDialog(null, "Compra no seleccionado");
            }else{
                String idCompra=(String)TablaDatosCompra.getValueAt(fila,0).toString();
                String idProveedor=(String)TablaDatosCompra.getValueAt(fila,1);
                String fechaCompra=(String)TablaDatosCompra.getValueAt(fila,2);
                String numeroFactura=(String)TablaDatosCompra.getValueAt(fila,3);
                String montoTotal=(String)TablaDatosCompra.getValueAt(fila,4);                
                this.txtid_compra.setText(idCompra);
                this.txtid_proveedor.setText(idProveedor);
                this.txtfecha_compra.setText(fechaCompra);
                this.txtnumero_factura.setText(numeroFactura);
                this.txtmonto_total.setText(montoTotal);                
            }
        }catch(Exception e){
            Util.printException("fcompra.TablaDatosCompraMouseClicked", e);
        }          
    }//GEN-LAST:event_TablaDatosCompraMouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        agregar();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        modificar();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiaCampos();
    }//GEN-LAST:event_btnNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fcompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fcompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fcompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fcompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fcompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaDatosCompra;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblfecha_compra;
    private javax.swing.JLabel lblid_compra;
    private javax.swing.JLabel lblid_proveedor;
    private javax.swing.JLabel lblmonto_total;
    private javax.swing.JLabel lblnumero_facctura;
    private javax.swing.JTextField txtfecha_compra;
    private javax.swing.JTextField txtid_compra;
    private javax.swing.JTextField txtid_proveedor;
    private javax.swing.JTextField txtmonto_total;
    private javax.swing.JTextField txtnumero_factura;
    // End of variables declaration//GEN-END:variables


    private void limpiaCampos() {
        try{
            this.txtid_compra.setText("");
            this.txtid_proveedor.setText("");
            this.txtfecha_compra.setText("");
            this.txtnumero_factura.setText("");
            this.txtmonto_total.setText("");
        }catch(Exception e){
            Util.printException("fcompra.limpiaCampos", e);
        }                
    }
    
    
    public void limpiaTabla(){
        int filaRestante=0;
        try{        
            for(int i=0;i<=TablaDatosCompra.getRowCount();i++){
                modelo.removeRow(i);
                i = i - 1;
                filaRestante=modelo.getRowCount();
                if(filaRestante==0){
                    break;
                }
            }
        }catch(Exception e){
            Util.printException("fcompra.limpiaTabla", e);
        }        
    }

    private void llenaListado() {
        List<compra> listaAccesos = null;
        
        try{
            cDAO = new compraDAO();
            listaAccesos = new ArrayList<>();
            listaAccesos = cDAO.seleccionaTodo();

            Object[]pObj=new Object[5];

            modelo = (DefaultTableModel)TablaDatosCompra.getModel();

            for(compra p:listaAccesos){
                pObj[0] = p.getId_compra();
                pObj[1] = p.getId_proveedor();
                pObj[2] = p.getFecha_compra();
                pObj[3] = p.getNumero_factura();
                pObj[4] = p.getMonto_total();
                
                modelo.addRow(pObj);
            }            
            TablaDatosCompra.setModel(modelo);
        }catch(Exception e){
            Util.printException("fcompra.llenaListado", e);
        }
    }

    
    
    private void agregar(){
        
        try{
            miCompra = new compra(  Util.str2int(this.txtid_compra.getText()),
                                    Util.str2int(this.txtid_proveedor.getText()),
                                    Util.str2date(this.txtfecha_compra.getText()),
                                    this.txtnumero_factura.getText(),
                                    Util.str2double(this.txtmonto_total.getText() ) );
            
            if ( cDAO.inserta( miCompra ) ){
                JOptionPane.showMessageDialog(null, "Compra ingresada");
                limpiaTabla();
                limpiaCampos();
                llenaListado();
            }
 
        }catch(Exception e){
            Util.printException("fcompra.agregar", e);
        }
    }
    
    private void modificar(){
        try{
            miCompra = new compra(  Util.str2int(this.txtid_compra.getText()),
                                    Util.str2int(this.txtid_proveedor.getText()),
                                    Util.str2date(this.txtfecha_compra.getText()),
                                    this.txtnumero_factura.getText(),
                                    Util.str2double(this.txtmonto_total.getText() ) );
            
            if ( cDAO.actualiza(miCompra) ){
                JOptionPane.showMessageDialog(null, "Compra actualizada");
                limpiaTabla();
                limpiaCampos();
                llenaListado();
            }

        }catch(Exception e){
            Util.printException("fcompra.modificar", e);
        }
    }
    
    

    private void eliminar(){
        try{        
            fila = TablaDatosCompra.getSelectedRow();
            if(fila == -1){
                JOptionPane.showMessageDialog(null, "Debe seleccionar fila");
            }else{
                if ( cDAO.elimina( Util.str2int((String)TablaDatosCompra.getValueAt(fila,0).toString()) ) ){
                    JOptionPane.showMessageDialog(null, "Compra eliminada");
                    limpiaTabla();
                    limpiaCampos();
                    llenaListado();
                }
            }
        }catch(Exception e){
            Util.printException("fcompra.eliminar", e);
        }        
    }    
 
}
