/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.portales.domingo.progra2.grupo12.farmaciajutiapa.vista;

/**
 *
 * @author josea
 */
public class fPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form fPrincipal
     */
    public fPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miEstadoCivil = new javax.swing.JMenuItem();
        miGenero = new javax.swing.JMenuItem();
        miAcceso = new javax.swing.JMenuItem();
        miAcceso_rol = new javax.swing.JMenuItem();
        miEmpresa = new javax.swing.JMenuItem();
        miMarca_producto = new javax.swing.JMenuItem();
        miRol = new javax.swing.JMenuItem();
        miTipo_Producto = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miPersona = new javax.swing.JMenuItem();
        miCliente = new javax.swing.JMenuItem();
        miCompra_detalle = new javax.swing.JMenuItem();
        miOferta = new javax.swing.JMenuItem();
        miProducto = new javax.swing.JMenuItem();
        miProveedor = new javax.swing.JMenuItem();
        miUsuario = new javax.swing.JMenuItem();
        miVenta = new javax.swing.JMenuItem();
        miVenta_detalle = new javax.swing.JMenuItem();
        miCompra = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Mantenimientos Simples");

        miEstadoCivil.setText("Estado civil");
        miEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEstadoCivilActionPerformed(evt);
            }
        });
        jMenu1.add(miEstadoCivil);

        miGenero.setText("Genero");
        miGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGeneroActionPerformed(evt);
            }
        });
        jMenu1.add(miGenero);

        miAcceso.setText("Acceso");
        miAcceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAccesoActionPerformed(evt);
            }
        });
        jMenu1.add(miAcceso);

        miAcceso_rol.setText("Acceso Rol");
        miAcceso_rol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAcceso_rolActionPerformed(evt);
            }
        });
        jMenu1.add(miAcceso_rol);

        miEmpresa.setText("Empresa");
        miEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEmpresaActionPerformed(evt);
            }
        });
        jMenu1.add(miEmpresa);

        miMarca_producto.setText("Marca Producto");
        miMarca_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMarca_productoActionPerformed(evt);
            }
        });
        jMenu1.add(miMarca_producto);

        miRol.setText("Rol");
        miRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRolActionPerformed(evt);
            }
        });
        jMenu1.add(miRol);

        miTipo_Producto.setText("Tipo Producto");
        miTipo_Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTipo_ProductoActionPerformed(evt);
            }
        });
        jMenu1.add(miTipo_Producto);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Mantenimientos Complejos");

        miPersona.setText("Persona");
        miPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPersonaActionPerformed(evt);
            }
        });
        jMenu2.add(miPersona);

        miCliente.setText("Cliente");
        miCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miClienteActionPerformed(evt);
            }
        });
        jMenu2.add(miCliente);

        miCompra_detalle.setText("Compra Detalle");
        miCompra_detalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCompra_detalleActionPerformed(evt);
            }
        });
        jMenu2.add(miCompra_detalle);

        miOferta.setText("Oferta");
        miOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miOfertaActionPerformed(evt);
            }
        });
        jMenu2.add(miOferta);

        miProducto.setText("Producto");
        miProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProductoActionPerformed(evt);
            }
        });
        jMenu2.add(miProducto);

        miProveedor.setText("Proveedores");
        miProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProveedorActionPerformed(evt);
            }
        });
        jMenu2.add(miProveedor);

        miUsuario.setText("Usuario");
        miUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUsuarioActionPerformed(evt);
            }
        });
        jMenu2.add(miUsuario);

        miVenta.setText("Venta");
        miVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVentaActionPerformed(evt);
            }
        });
        jMenu2.add(miVenta);

        miVenta_detalle.setText("Venta Detalle");
        miVenta_detalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVenta_detalleActionPerformed(evt);
            }
        });
        jMenu2.add(miVenta_detalle);

        miCompra.setText("Compra");
        miCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCompraActionPerformed(evt);
            }
        });
        jMenu2.add(miCompra);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEstadoCivilActionPerformed
       festado_civil fec= new festado_civil();
       fec.setVisible(true);
    }//GEN-LAST:event_miEstadoCivilActionPerformed

    private void miGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGeneroActionPerformed
        fgenero fg= new fgenero();
        fg.setVisible(true);
    }//GEN-LAST:event_miGeneroActionPerformed

    private void miPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPersonaActionPerformed
        fpersona fp= new fpersona();
        fp.setVisible(true);
    }//GEN-LAST:event_miPersonaActionPerformed

    private void miAccesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAccesoActionPerformed
        facceso fa= new facceso();
        fa.setVisible(true);
    }//GEN-LAST:event_miAccesoActionPerformed

    private void miClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miClienteActionPerformed
        fcliente_1 cli= new fcliente_1();
        cli.setVisible(true);
    }//GEN-LAST:event_miClienteActionPerformed

    private void miCompra_detalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCompra_detalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miCompra_detalleActionPerformed

    private void miEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEmpresaActionPerformed
        fempresa_1 em= new fempresa_1();
        em.setVisible(true);
    }//GEN-LAST:event_miEmpresaActionPerformed

    private void miMarca_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMarca_productoActionPerformed
       fmarca_producto mar= new fmarca_producto();
        mar.setVisible(true);
    }//GEN-LAST:event_miMarca_productoActionPerformed

    private void miOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miOfertaActionPerformed
       foferta_1 of= new foferta_1();
        of.setVisible(true);
    }//GEN-LAST:event_miOfertaActionPerformed

    private void miAcceso_rolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAcceso_rolActionPerformed
        facceso_rol ar= new  facceso_rol();
        ar.setVisible(true);
    }//GEN-LAST:event_miAcceso_rolActionPerformed

    private void miProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProductoActionPerformed
       fproducto pro= new  fproducto();
        pro.setVisible(true);
    }//GEN-LAST:event_miProductoActionPerformed

    private void miProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProveedorActionPerformed
        fproveedores proveedor= new  fproveedores();
        proveedor.setVisible(true);
    }//GEN-LAST:event_miProveedorActionPerformed

    private void miRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRolActionPerformed
        frol_1 rol= new  frol_1();
        rol.setVisible(true);
    }//GEN-LAST:event_miRolActionPerformed

    private void miTipo_ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTipo_ProductoActionPerformed
       ftipo_producto tipP= new  ftipo_producto();
        tipP.setVisible(true);
    }//GEN-LAST:event_miTipo_ProductoActionPerformed

    private void miUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUsuarioActionPerformed
       fusuario_1 us= new  fusuario_1();
        us.setVisible(true);
    }//GEN-LAST:event_miUsuarioActionPerformed

    private void miVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVentaActionPerformed
       fventa_1 ve= new  fventa_1();
        ve.setVisible(true);
    }//GEN-LAST:event_miVentaActionPerformed

    private void miVenta_detalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVenta_detalleActionPerformed
       fventa_detalle_1 veD= new  fventa_detalle_1();
        veD.setVisible(true);
    }//GEN-LAST:event_miVenta_detalleActionPerformed

    private void miCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCompraActionPerformed
       fcompra comp= new  fcompra();
        comp.setVisible(true);
    }//GEN-LAST:event_miCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem miAcceso;
    private javax.swing.JMenuItem miAcceso_rol;
    private javax.swing.JMenuItem miCliente;
    private javax.swing.JMenuItem miCompra;
    private javax.swing.JMenuItem miCompra_detalle;
    private javax.swing.JMenuItem miEmpresa;
    private javax.swing.JMenuItem miEstadoCivil;
    private javax.swing.JMenuItem miGenero;
    private javax.swing.JMenuItem miMarca_producto;
    private javax.swing.JMenuItem miOferta;
    private javax.swing.JMenuItem miPersona;
    private javax.swing.JMenuItem miProducto;
    private javax.swing.JMenuItem miProveedor;
    private javax.swing.JMenuItem miRol;
    private javax.swing.JMenuItem miTipo_Producto;
    private javax.swing.JMenuItem miUsuario;
    private javax.swing.JMenuItem miVenta;
    private javax.swing.JMenuItem miVenta_detalle;
    // End of variables declaration//GEN-END:variables
}
