/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.portales.domingo.progra2.grupo12.farmaciajutiapa.vista;

import com.portales.domingo.progra2.grupo12.farmaciajutiapa.controlador.Util;
import com.portales.domingo.progra2.grupo12.farmaciajutiapa.dao.venta_detalleDAO;
import com.portales.domingo.progra2.grupo12.farmaciajutiapa.modelo.venta_detalle;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Edinson Ruano
 */
public class fventa_detalle_1 extends javax.swing.JFrame {
    private venta_detalleDAO vdDAO = null;
    private venta_detalle miVentaDet=null;
    private DefaultTableModel modelo=null;
    private int fila = 0;

    /**
     * Creates new form fventa_detalle
     */
    public fventa_detalle_1() {
        initComponents();
        
        //Permite cerrar la BD cuando se cierra la ventana
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent event) {
                if(vdDAO!=null)
                    vdDAO.cierra();
                    dispose();
            }
        });

        llenaListado();
        limpiaCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblide_venta_detalle = new javax.swing.JLabel();
        txtide_venta_detalle = new javax.swing.JTextField();
        lblid_venta = new javax.swing.JLabel();
        txtid_venta = new javax.swing.JTextField();
        lblid_marca_producto_venta = new javax.swing.JLabel();
        txtid_marca_producto_venta = new javax.swing.JTextField();
        lblid_tipo_producto_venta = new javax.swing.JLabel();
        txtid_tipo_producto_venta = new javax.swing.JTextField();
        lblid_producto_venta = new javax.swing.JLabel();
        txtid_producto_venta = new javax.swing.JTextField();
        lblprecio_unitario_venta = new javax.swing.JLabel();
        txtprecio_unitario_venta = new javax.swing.JTextField();
        lblcantidad_venta = new javax.swing.JLabel();
        txtcantidad_venta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDatosVentaDetalle = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Mantenimiento de venta detalle");

        lblide_venta_detalle.setText("Id venta detalle");

        txtide_venta_detalle.setEditable(false);

        lblid_venta.setText("Id venta");

        lblid_marca_producto_venta.setText("Id marca producto");

        lblid_tipo_producto_venta.setText("Id tipo producto");

        lblid_producto_venta.setText("Id producto");

        lblprecio_unitario_venta.setText("Precio unitario venta");

        lblcantidad_venta.setText("Cantidad");

        TablaDatosVentaDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Venta Detalle", "Id Venta", "Id Marca Producto", "Id Tipo Producto", "Id Producto", "Precio Unitario Venta", "Cantidad"
            }
        ));
        TablaDatosVentaDetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDatosVentaDetalleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaDatosVentaDetalle);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblide_venta_detalle)
                            .addComponent(lblid_venta)
                            .addComponent(lblid_marca_producto_venta)
                            .addComponent(lblid_tipo_producto_venta)
                            .addComponent(lblid_producto_venta))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtide_venta_detalle, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(txtid_venta)
                            .addComponent(txtid_marca_producto_venta)
                            .addComponent(txtid_tipo_producto_venta)
                            .addComponent(txtid_producto_venta)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblprecio_unitario_venta)
                            .addComponent(lblcantidad_venta))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtprecio_unitario_venta, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(txtcantidad_venta))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNuevo)))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblide_venta_detalle)
                            .addComponent(txtide_venta_detalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblid_venta)
                            .addComponent(txtid_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtid_marca_producto_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblid_marca_producto_venta))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblid_tipo_producto_venta)
                            .addComponent(txtid_tipo_producto_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblid_producto_venta)
                            .addComponent(txtid_producto_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblprecio_unitario_venta)
                    .addComponent(txtprecio_unitario_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblcantidad_venta)
                            .addComponent(txtcantidad_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregar)
                            .addComponent(btnModificar)
                            .addComponent(btnEliminar)
                            .addComponent(btnNuevo))))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        agregar();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        modificar();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiaCampos();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void TablaDatosVentaDetalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDatosVentaDetalleMouseClicked
        try{
            fila = TablaDatosVentaDetalle.getSelectedRow();
            if(fila == -1){
                JOptionPane.showMessageDialog(null, "Venta detalle no seleccionado");
            }else{
                String idVentaDetalle=(String)TablaDatosVentaDetalle.getValueAt(fila,0).toString();
                String idVenta=(String)TablaDatosVentaDetalle.getValueAt(fila,1);
                String idMarcaProd=(String)TablaDatosVentaDetalle.getValueAt(fila,2);
                String idTipoProd=(String)TablaDatosVentaDetalle.getValueAt(fila,3).toString();
                String idProd=(String)TablaDatosVentaDetalle.getValueAt(fila,4);
                String precioUnitarioVenta=(String)TablaDatosVentaDetalle.getValueAt(fila,5);
                String cantidad=(String)TablaDatosVentaDetalle.getValueAt(fila,6);
                this.txtide_venta_detalle.setText(idVentaDetalle);
                this.txtid_venta.setText(idVenta);
                this.txtid_marca_producto_venta.setText(idMarcaProd);
                this.txtid_tipo_producto_venta.setText(idTipoProd);
                this.txtid_producto_venta.setText(idProd);
                this.txtprecio_unitario_venta.setText(precioUnitarioVenta);                
                this.txtcantidad_venta.setText(cantidad);                                
            }
        }catch(Exception e){
            Util.printException("fventa_detalle_1.TablaDatosAccesoMouseClicked", e);
        } 
    }//GEN-LAST:event_TablaDatosVentaDetalleMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fventa_detalle_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fventa_detalle_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fventa_detalle_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fventa_detalle_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fventa_detalle_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaDatosVentaDetalle;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcantidad_venta;
    private javax.swing.JLabel lblid_marca_producto_venta;
    private javax.swing.JLabel lblid_producto_venta;
    private javax.swing.JLabel lblid_tipo_producto_venta;
    private javax.swing.JLabel lblid_venta;
    private javax.swing.JLabel lblide_venta_detalle;
    private javax.swing.JLabel lblprecio_unitario_venta;
    private javax.swing.JTextField txtcantidad_venta;
    private javax.swing.JTextField txtid_marca_producto_venta;
    private javax.swing.JTextField txtid_producto_venta;
    private javax.swing.JTextField txtid_tipo_producto_venta;
    private javax.swing.JTextField txtid_venta;
    private javax.swing.JTextField txtide_venta_detalle;
    private javax.swing.JTextField txtprecio_unitario_venta;
    // End of variables declaration//GEN-END:variables


    private void limpiaCampos() {
        try{
            this.txtide_venta_detalle.setText("");
            this.txtid_venta.setText("");
            this.txtid_marca_producto_venta.setText("");
            this.txtid_tipo_producto_venta.setText("");
            this.txtid_producto_venta.setText("");
            this.txtprecio_unitario_venta.setText("");             
            this.txtcantidad_venta.setText("");
        }catch(Exception e){
            Util.printException("fventa_detalle_1.limpiaCampos", e);
        }                
    }
    
    
    public void limpiaTabla(){
        int filaRestante=0;
        try{        
            for(int i=0;i<=TablaDatosVentaDetalle.getRowCount();i++){
                modelo.removeRow(i);
                i = i - 1;
                filaRestante=modelo.getRowCount();
                if(filaRestante==0){
                    break;
                }
            }
        }catch(Exception e){
            Util.printException("fventa_detalle_1.limpiaTabla", e);
        }        
    }

    private void llenaListado() {
        List<venta_detalle> listaAccesos = null;
        
        try{
            vdDAO = new venta_detalleDAO();
            listaAccesos = new ArrayList<>();
            listaAccesos = vdDAO.seleccionaTodo();

            Object[]pObj=new Object[7];

            modelo = (DefaultTableModel)TablaDatosVentaDetalle.getModel();

            for(venta_detalle p:listaAccesos){
                pObj[0] = p.getId_venta_detalle();
                pObj[1] = p.getId_venta();
                pObj[2] = p.getId_marca_producto();
                pObj[3] = p.getId_tipo_producto();
                pObj[4] = p.getId_producto();
                pObj[5] = p.getPrecio_unitario_venta();
                pObj[6] = p.getCantidad();                
                modelo.addRow(pObj);
            }
            TablaDatosVentaDetalle.setModel(modelo);
        }catch(Exception e){
            Util.printException("fventa_detalle_1.llenaListado", e);
        }
    }

    
    
    private void agregar(){
        
        try{
            miVentaDet = new venta_detalle( Util.str2int( this.txtide_venta_detalle.getText() ),
                                            Util.str2int( this.txtid_venta.getText() ),
                                            Util.str2int( this.txtid_marca_producto_venta.getText() ),
                                            Util.str2int( this.txtid_tipo_producto_venta.getText() ),
                                            Util.str2int( this.txtid_producto_venta.getText() ),
                                            Util.str2double(this.txtprecio_unitario_venta.getText() ),       
                                            Util.str2int( this.txtcantidad_venta.getText() ) );
            
            if ( vdDAO.inserta(miVentaDet) ){
                JOptionPane.showMessageDialog(null, "Venta detalle ingresado");
                limpiaTabla();
                limpiaCampos();
                llenaListado();
            }
                    
            
        }catch(Exception e){
            Util.printException("fventa_detalle_1.agregar", e);
        }
    }
    
    private void modificar(){
        try{
            miVentaDet = new venta_detalle( Util.str2int( this.txtide_venta_detalle.getText() ),
                                            Util.str2int( this.txtid_venta.getText() ),
                                            Util.str2int( this.txtid_marca_producto_venta.getText() ),
                                            Util.str2int( this.txtid_tipo_producto_venta.getText() ),
                                            Util.str2int( this.txtid_producto_venta.getText() ),
                                            Util.str2double(this.txtprecio_unitario_venta.getText() ),       
                                            Util.str2int( this.txtcantidad_venta.getText() ) );
            
            if ( vdDAO.actualiza(miVentaDet) ){
                JOptionPane.showMessageDialog(null, "Venta detalle actualizado");
                limpiaTabla();
                limpiaCampos();
                llenaListado();
            }

        }catch(Exception e){
            Util.printException("fventa_detalle_1.modificar", e);
        }
    }
    
    

    private void eliminar(){
        try{        
            fila = TablaDatosVentaDetalle.getSelectedRow();
            if(fila == -1){
                JOptionPane.showMessageDialog(null, "Debe seleccionar fila");
            }else{
                if ( vdDAO.elimina( Util.str2int((String)TablaDatosVentaDetalle.getValueAt(fila,0).toString()) ) ){
                    JOptionPane.showMessageDialog(null, "Venta detalle eliminado");
                    limpiaTabla();
                    limpiaCampos();
                    llenaListado();
                }
            }
        }catch(Exception e){
            Util.printException("fventa_detalle_1.eliminar", e);
        }        
    }    
  
}
